name: Spellcheck Action
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.6.0